[tool.poetry]
name = "fineknp"
version = "0.1.0"
description = ""
authors = ["matsurih"]

[tool.poetry.dependencies]
python = "^3.6"
pyknp = "^0.4.5"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
